Diploma for verification
SergeiGlinisty/Salesforce_SergeyGlinisty pull request #5
Opened 2022-09-18 20:42 UTC by SergeiGlinisty

Please check

2022-09-19 19:47 UTC, voropa requested changes

2022-09-19 19:47 UTC, voropa commented on src/test/java/elements/LightningFormatedElement.java
> +        log.debug("Get text from LightningFormatedElement field");
Не пишите статичные сообщение в лог, они же вам никак не помогут анлизе падения тестов, потому что непонятно будет из какого элемента что пыталось взять. Добавляйте в лог-сообщение иформацию о конкретном элементе, с которым идет взаимодействие, Например тут:
log.debug("Get text from %s field", label);

У вас во  многих классах-декораторах подобная ошибка, перепроверьте их все

2022-09-19 19:47 UTC, voropa commented on src/test/java/elements/OpportunityCombobox.java
> +        if (Objects.nonNull(visibleText)) {
Вторая проверка н nonNull тут лишняя

2022-09-19 19:47 UTC, voropa commented on src/test/java/elements/OpportunitySearchInput.java
> +        log.debug("Go to the search input field");
Тут та же проблема с логированием - логируете статичные сообщения, вместо этого нужно писать:
log.debug("Setting %s value to %s input", value, label);

2022-09-19 19:47 UTC, voropa commented on src/test/java/pages/EntityBasePage.java
> +    public final static By POPUP_LOCATOR_SAVE = By.xpath("//div/span[contains(text(),' was saved')]");
Почему у вас половина локаторов - public? Локаторы должны быть инкапсулированы внутри page клаасса и использоваться только  внутри методов страницы

2022-09-19 19:47 UTC, voropa commented on src/test/java/pages/tasks/TasksPage.java
> +    public final static By TASKS_PAGE_LOCATOR = By.xpath("//span[@class='triggerLinkText selectedListView slds-page-header__title slds-truncate slds-p-right--xx-small uiOutputText']");
Это очень плохой локатор, потому что он перестанет работать, как только разработчика добавят еще один class атрибут к этому элементу, переделайте его

2022-09-19 19:47 UTC, voropa commented on src/test/java/pages/tasks/TasksPage.java
>      public final static By TASKS_DROPDOWN_ICON = By.xpath("//a[@title='Show one more action' and @class='slds-button slds-button--icon-x-small slds-button--icon-border-filled']");
Тут то же самое с локатором

2022-09-19 19:47 UTC, voropa commented on src/test/java/tests/CaseTest.java
> +        opportunitiesPage = new OpportunitiesPage(driver);
У вас же уже и так создаются обьекты всех страниц в beforeClass методе в BaseTest, зачем их создавать еще раз

2022-09-19 19:47 UTC, voropa commented on src/test/java/utils/TestListener.java
> +    @Step("Starting test")
Это же не шаги теста, тут не нужно добавлять allure @step аннотации)

2022-09-22 08:52 UTC, voropa requested changes
пройдитесь еще раз внимательно по всем классам-декораторам, у вас там в некоторых по-прежнему лишние if и логи

2022-09-22 08:52 UTC, voropa commented on src/test/java/elements/AccountDropDown.java
>          if (Objects.nonNull(visibleText)) {
Лишняя проверка на null

2022-09-22 08:52 UTC, voropa commented on src/test/java/elements/AccountDropDown.java
>          log.debug("Select the desired option");
Лишний лог, у вас же ниже  пишется лог, какой конкретно option выбирается

2022-09-22 08:52 UTC, voropa commented on src/test/java/elements/CaseDropdown.java
>          if (Objects.nonNull(visibleText)) {
лишний if

2022-09-22 08:52 UTC, voropa commented on src/test/java/elements/ContactSearchInput.java
> +                .until(ExpectedConditions.presenceOfElementLocated(By.xpath(String.format("//ul[@role='group']",label))));
Зачем тут String.foermat(), у вас же локатор без параметров

2022-09-22 08:52 UTC, voropa commented on src/test/java/elements/LightningCombobox.java
>          if (Objects.nonNull(visibleText)) {
Лишний if

2022-09-22 09:29 UTC, voropa commented
Запустил ваши тесты через mvn clean test несколько раз: 4-5 тестов падают. Исправляйте, тесты должны стабильно проходить, если в системе нет багов
<img width="1677" alt="image" src="https://user-images.githubusercontent.com/14195681/191711384-39ba00b0-cdb4-43b0-b149-f595b3e9a2ba.png">

2022-09-24 20:06 UTC, voropa commented on src/test/java/tests/OpportunityTest.java
> +        Thread.sleep(5000);
Плохо, конечно, что у вас Thread.sleep() в тестах используется, их по-хорошему нужно заменить н явные ожидания чего-то

2022-09-24 21:16 UTC, SergeiGlinisty commented
Олег, я понимаю что плохо, я использую явные ожидания
opportunitiesPage.waitForEntityDropdownIcon(),
тут дело в том, что чтобы тесты работали стабильно почему-то перед
некоторыми шагами теста нужно просто подождать некоторое время.

сб, 24 сент. 2022 г. в 23:06, Oleg Voropaev ***@***.***>:

> ***@***.**** commented on this pull request.
> ------------------------------
>
> In src/test/java/tests/OpportunityTest.java
> <https://github.com/SergeiGlinisty/Salesforce_SergeyGlinisty/pull/5#discussion_r979298159>
> :
>
> >
>
> +        homePage.waitForOpportunityTab();
>
> +        homePage.openOpportunityTabJs();
>
> +        opportunitiesPage.waitForEntityDropdownIcon();
>
> +        Thread.sleep(5000);
>
>
> Плохо, конечно, что у вас Thread.sleep() в тестах используется, их
> по-хорошему нужно заменить н явные ожидания чего-то
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/SergeiGlinisty/Salesforce_SergeyGlinisty/pull/5#pullrequestreview-1119329653>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AZCHSQQVKP3MLRSS7X64J33V75NNHANCNFSM6AAAAAAQPS7C34>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***
> com>
>

2022-09-24 23:04 UTC, voropa commented
У меня по-прежнему падает 4 теста, причем 2 из них на assert'ах, а так не должно быть, если в приложении нет багов. 
<img width="1679" alt="image" src="https://user-images.githubusercontent.com/14195681/192121600-7fa63b1b-8025-4318-8ae3-e13d6996f60c.png">

2022-09-25 08:59 UTC, SergeiGlinisty commented
Посмотрел, в Smoke CaseTest перестало кликать второй раз  по кнопке вкладки
Cases на homePage во время прохождения теста, сделал попробовал CopyPath
этого шага всё заработало.Так и не понял, почему второй раз не кликало, с
локатором всё хорошо. Negative CaseTest и TaskTest у меня не падает. Сделал
3 подряд пуска, всё Ок

вс, 25 сент. 2022 г. в 02:04, Oleg Voropaev ***@***.***>:

> У меня по-прежнему падает 4 теста, причем 2 из них на assert'ах, а так не
> должно быть, если в приложении нет багов.
> [image: image]
> <https://user-images.githubusercontent.com/14195681/192121600-7fa63b1b-8025-4318-8ae3-e13d6996f60c.png>
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/SergeiGlinisty/Salesforce_SergeyGlinisty/pull/5#issuecomment-1257079617>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AZCHSQTKFWMNPAIXAEJOIADV76CHPANCNFSM6AAAAAAQPS7C34>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2022-09-25 09:37 UTC, SergeiGlinisty commented
Вот ещё 3 раза подряд запустил

вс, 25 сент. 2022 г. в 11:59, Сергей Глинистый ***@***.***>:

> Посмотрел, в Smoke CaseTest перестало кликать второй раз  по кнопке
> вкладки Cases на homePage во время прохождения теста, сделал попробовал
> CopyPath этого шага всё заработало.Так и не понял, почему второй раз не
> кликало, с локатором всё хорошо. Negative CaseTest и TaskTest у меня не
> падает. Сделал 3 подряд пуска, всё Ок
>
> вс, 25 сент. 2022 г. в 02:04, Oleg Voropaev ***@***.***>:
>
>> У меня по-прежнему падает 4 теста, причем 2 из них на assert'ах, а так не
>> должно быть, если в приложении нет багов.
>> [image: image]
>> <https://user-images.githubusercontent.com/14195681/192121600-7fa63b1b-8025-4318-8ae3-e13d6996f60c.png>
>>
>> —
>> Reply to this email directly, view it on GitHub
>> <https://github.com/SergeiGlinisty/Salesforce_SergeyGlinisty/pull/5#issuecomment-1257079617>,
>> or unsubscribe
>> <https://github.com/notifications/unsubscribe-auth/AZCHSQTKFWMNPAIXAEJOIADV76CHPANCNFSM6AAAAAAQPS7C34>
>> .
>> You are receiving this because you authored the thread.Message ID:
>> ***@***.***>
>>
>

2022-09-25 10:00 UTC, SergeiGlinisty commented
и ещё сразу 2 раза запустил после предыдущего сообщения

вс, 25 сент. 2022 г. в 12:37, Сергей Глинистый ***@***.***>:

> Вот ещё 3 раза подряд запустил
>
> вс, 25 сент. 2022 г. в 11:59, Сергей Глинистый ***@***.***
> >:
>
>> Посмотрел, в Smoke CaseTest перестало кликать второй раз  по кнопке
>> вкладки Cases на homePage во время прохождения теста, сделал попробовал
>> CopyPath этого шага всё заработало.Так и не понял, почему второй раз не
>> кликало, с локатором всё хорошо. Negative CaseTest и TaskTest у меня не
>> падает. Сделал 3 подряд пуска, всё Ок
>>
>> вс, 25 сент. 2022 г. в 02:04, Oleg Voropaev ***@***.***>:
>>
>>> У меня по-прежнему падает 4 теста, причем 2 из них на assert'ах, а так
>>> не должно быть, если в приложении нет багов.
>>> [image: image]
>>> <https://user-images.githubusercontent.com/14195681/192121600-7fa63b1b-8025-4318-8ae3-e13d6996f60c.png>
>>>
>>> —
>>> Reply to this email directly, view it on GitHub
>>> <https://github.com/SergeiGlinisty/Salesforce_SergeyGlinisty/pull/5#issuecomment-1257079617>,
>>> or unsubscribe
>>> <https://github.com/notifications/unsubscribe-auth/AZCHSQTKFWMNPAIXAEJOIADV76CHPANCNFSM6AAAAAAQPS7C34>
>>> .
>>> You are receiving this because you authored the thread.Message ID:
>>> ***@***.***>
>>>
>>

2022-09-25 13:01 UTC, voropa commented
Все же стабильно оно не работает у вас. Да, salesforce не простой в этом плане, в нем очень много нестабильности и нужно очень заморочиться с ожиданиями  при написании тестов. Но в конечном итоге, по моему опыту, можно добиться от него стабильного выполнения тестов. Собственно поэтому он и был помечен как (сложный) в списке дипломных проектов. 
Оставляйте уже как есть, но в будущем, замените хотя бы thread.sleep() на явные ожидания, чтобы не стыдно было показывать этот проект кому-либо)
И еще порезолвайте конфликты, чтобы смержить эту ветку в master.

2022-09-25 13:36 UTC, SergeiGlinisty commented
Спасибо Олег, thread.sleep() обязательно заменю.

вс, 25 сент. 2022 г. в 16:02, Oleg Voropaev ***@***.***>:

> Все же стабильно оно не работает у вас. Да, salesforce не простой в этом
> плане, в нем очень много нестабильности и нужно очень заморочиться с
> ожиданиями при написании тестов. Но в конечном итоге, по моему опыту, можно
> добиться от него стабильного выполнения тестов. Собственно поэтому он и был
> помечен как (сложный) в списке дипломных проектов.
> Оставляйте уже как есть, но в будущем, замените хотя бы thread.sleep() на
> явные ожидания, чтобы не стыдно было показывать этот проект кому-либо)
> И еще порезолвайте конфликты, чтобы смержить эту ветку в master.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/SergeiGlinisty/Salesforce_SergeyGlinisty/pull/5#issuecomment-1257189822>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AZCHSQVOZJ7A5NKS5BY627DWABEMVANCNFSM6AAAAAAQPS7C34>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2022-09-26 16:54 UTC, merged